"""
Alias Manager - High-level alias operations.
"""

from typing import Optional, List, Dict, Any
from pathlib import Path
import os

from aliasforge.core.database import Database


class AliasManager:
    """High-level alias management operations."""
    
    SHELL_CONFIG_FILES = {
        "bash": [".bashrc", ".bash_aliases"],
        "zsh": [".zshrc"],
        "fish": [".config/fish/config.fish"]
    }
    
    def __init__(self, db: Optional[Database] = None):
        """Initialize alias manager.
        
        Args:
            db: Database instance. If None, creates a new one.
        """
        self.db = db or Database()
    
    def add(
        self,
        name: str,
        command: str,
        description: str = "",
        tags: Optional[List[str]] = None,
        shell: str = "all",
        group: str = "default"
    ) -> Dict[str, Any]:
        """Add a new alias.
        
        Args:
            name: Alias name
            command: Command to execute
            description: Optional description
            tags: Optional list of tags
            shell: Target shell (bash/zsh/fish/all)
            group: Group name
            
        Returns:
            Created alias dict
        """
        alias_id = self.db.add_alias(name, command, description, tags, shell, group)
        return self.db.get_alias(name)
    
    def get(self, name: str) -> Optional[Dict[str, Any]]:
        """Get alias by name."""
        return self.db.get_alias(name)
    
    def list(
        self,
        group: Optional[str] = None,
        shell: Optional[str] = None,
        tag: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """List all aliases with optional filters."""
        return self.db.get_all_aliases(group, shell, tag)
    
    def update(
        self,
        name: str,
        command: Optional[str] = None,
        description: Optional[str] = None,
        tags: Optional[List[str]] = None,
        shell: Optional[str] = None,
        group: Optional[str] = None
    ) -> bool:
        """Update an existing alias."""
        return self.db.update_alias(name, command, description, tags, shell, group)
    
    def delete(self, name: str) -> bool:
        """Delete an alias."""
        return self.db.delete_alias(name)
    
    def search(self, query: str) -> List[Dict[str, Any]]:
        """Search aliases."""
        return self.db.search_aliases(query)
    
    def get_groups(self) -> List[str]:
        """Get all group names."""
        return self.db.get_groups()
    
    def get_tags(self) -> List[str]:
        """Get all unique tags."""
        aliases = self.db.get_all_aliases()
        tags = set()
        for alias in aliases:
            tags.update(alias.get("tags", []))
        return sorted(tags)
    
    # ==================== Shell Integration ====================
    
    def detect_current_shell(self) -> str:
        """Detect the current shell.
        
        Returns:
            Shell name (bash/zsh/fish)
        """
        shell_path = os.environ.get("SHELL", "")
        if "zsh" in shell_path:
            return "zsh"
        elif "fish" in shell_path:
            return "fish"
        else:
            return "bash"
    
    def get_shell_config_path(self, shell: Optional[str] = None) -> Path:
        """Get the config file path for a shell.
        
        Args:
            shell: Shell name. If None, detects current shell.
            
        Returns:
            Path to shell config file
        """
        shell = shell or self.detect_current_shell()
        config_files = self.SHELL_CONFIG_FILES.get(shell, [".bashrc"])
        
        for config_file in config_files:
            path = Path.home() / config_file
            if path.exists():
                return path
        
        # Return default path even if it doesn't exist
        return Path.home() / config_files[0]
    
    def generate_shell_aliases(self, shell: Optional[str] = None) -> str:
        """Generate shell alias commands.
        
        Args:
            shell: Target shell. If None, generates for all shells.
            
        Returns:
            Shell alias commands string
        """
        aliases = self.db.get_all_aliases(shell=shell)
        lines = [
            "# ==================== AliasForge Aliases ====================",
            "# Generated by AliasForge - https://github.com/gitstq/AliasForge",
            ""
        ]
        
        for alias in aliases:
            # Add comment with description
            if alias.get("description"):
                lines.append(f"# {alias['description']}")
            
            # Generate alias command based on shell
            target_shell = shell or alias.get("shell", "all")
            if target_shell == "fish":
                lines.append(f"alias {alias['name']} '{alias['command']}'")
            else:
                # bash/zsh format
                lines.append(f"alias {alias['name']}='{alias['command']}'")
            lines.append("")
        
        lines.append("# ==================== End AliasForge Aliases ====================")
        
        return "\n".join(lines)
    
    def sync_to_shell(self, shell: Optional[str] = None) -> bool:
        """Sync aliases to shell config file.
        
        Args:
            shell: Target shell. If None, uses current shell.
            
        Returns:
            True if successful
        """
        shell = shell or self.detect_current_shell()
        config_path = self.get_shell_config_path(shell)
        
        # Read existing config
        if config_path.exists():
            content = config_path.read_text()
        else:
            content = ""
        
        # Remove old AliasForge section
        start_marker = "# ==================== AliasForge Aliases ===================="
        end_marker = "# ==================== End AliasForge Aliases ===================="
        
        start_idx = content.find(start_marker)
        end_idx = content.find(end_marker)
        
        if start_idx != -1 and end_idx != -1:
            # Remove old section including trailing newline
            content = content[:start_idx] + content[end_idx + len(end_marker):]
            # Clean up extra newlines
            content = content.rstrip("\n") + "\n\n"
        
        # Generate new aliases
        new_aliases = self.generate_shell_aliases(shell)
        
        # Append to config
        content = content.rstrip("\n") + "\n\n" + new_aliases + "\n"
        
        # Write back
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_path.write_text(content)
        
        return True
    
    # ==================== Import/Export ====================
    
    def export_to_file(self, file_path: Path, format: str = "yaml") -> bool:
        """Export aliases to a file.
        
        Args:
            file_path: Output file path
            format: Export format (yaml/json)
            
        Returns:
            True if successful
        """
        content = self.db.export_aliases(format)
        file_path.write_text(content)
        return True
    
    def import_from_file(self, file_path: Path) -> int:
        """Import aliases from a file.
        
        Args:
            file_path: Input file path
            
        Returns:
            Number of aliases imported
        """
        content = file_path.read_text()
        
        # Detect format from file extension
        if file_path.suffix == ".json":
            format = "json"
        else:
            format = "yaml"
        
        return self.db.import_aliases(content, format)
    
    # ==================== Backup/Restore ====================
    
    def create_backup(self, description: str = "") -> int:
        """Create a manual backup."""
        return self.db._create_backup("manual", description)
    
    def list_backups(self) -> List[Dict[str, Any]]:
        """List all backups."""
        return self.db.list_backups()
    
    def restore_backup(self, backup_id: int) -> bool:
        """Restore from a backup."""
        return self.db.restore_backup(backup_id)
    
    # ==================== Smart Suggestions ====================
    
    def suggest_from_history(self, history_lines: List[str], min_count: int = 3) -> List[Dict[str, Any]]:
        """Suggest aliases from command history.
        
        Args:
            history_lines: Lines from shell history
            min_count: Minimum occurrence count to suggest
            
        Returns:
            List of suggested alias dicts
        """
        from collections import Counter
        
        # Parse and count commands
        commands = []
        for line in history_lines:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            
            # Remove common prefixes
            for prefix in ["sudo ", "time ", "nice "]:
                if line.startswith(prefix):
                    line = line[len(prefix):]
                    break
            
            # Get the base command
            parts = line.split()
            if parts:
                commands.append(parts[0])
        
        # Count occurrences
        counter = Counter(commands)
        
        # Filter by minimum count and exclude existing aliases
        existing = {a["name"] for a in self.db.get_all_aliases()}
        suggestions = []
        
        for cmd, count in counter.most_common(20):
            if count >= min_count and cmd not in existing:
                suggestions.append({
                    "suggested_name": cmd[:10],  # Truncate long names
                    "command": cmd,
                    "usage_count": count,
                    "reason": f"Used {count} times in history"
                })
        
        return suggestions[:10]  # Top 10 suggestions
